name: json_to_model
description: Generate model class from Json file.
version: 3.0.0-beta.3
homepage: https://github.com/fadhilx/json_to_model

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  clock: ^1.1.0
  hive: ^2.0.4
  logging: ^1.0.1
  path: ^1.8.0
  quiver: ^3.0.1
  yaml: ^3.1.0
  process_run: ^0.12.1

dev_dependencies:
  build_runner: ^2.0.6
  hive_generator: ^1.1.0
  lint: ^1.5.1
  test: ^1.15.6
